feat: ffmpeg mapping
+ slight fixes

diff --git a/hayanime b/hayanime
--- a/hayanime
+++ b/hayanime
@@ -12,9 +12,7 @@
 # DISCLAIMER
 # I don't own or manage any server on the internet that scrapes by this tool,
 # and i'm not reponsible of any illegal uses of this tool.
-# this tool is for educational purposes only. Use at your own Risk
-#
-
+# This tool is for educational purposes only. Use at your own Risk.
 
 VERSION="v2.1.0"
 
@@ -137,22 +135,24 @@ dep_check(){
 }
 
 dl_manager(){
-	printf '%b' "\n"
 	case "${2}" in
 		*m3u8*|*master*|*manifest*)
 			dep_check "ffmpeg"
-			ffmpeg -loglevel error -stats -referer "${1}" -i "${2}" -c copy "${3}"
+			idx_comp "${2}"
+			ffmpeg -loglevel error -stats -referer "${1}" -i "${2}" -map "0:a:$((${qualvid:-1}-1))" -map "0:v:$((${qualvid:-1}-1))" -c copy "${3}"
 			;;
 		*)
 			dep_check "aria2c"
+			printf '%b' "\n"
 			aria2c -x 5 -s 5 --console-log-level=error --referer="${1}" --check-certificate="false" --download-result="hide" --auto-save-interval="0" "${2}" -o "${3}"
 			;;
 	esac
 	printf '%b\n' "\007"
-	suc "Downloading Episode ${epi_selected} Done!!"
+	[ "${?}" = "0" ] && suc "Downloading Episode ${epi_selected} Done!!" || err "Downloading Episode ${epi_selected} Failed..."
 }
 
 hist_handler(){
+	[ -e ~/.hayanihist ] || touch ~/.hayanihist 2>/dev/null		# Supress Incase of the Directory is Unwritable
 	if [ "${1}" = "append" ]; then
 		[ -w ~/.hayanihist ] || die "Hist file is Unwritable, Make sure you have access to write to HOME directory"
 		sed -i "/${3}/d" ~/.hayanihist
@@ -196,12 +196,12 @@ ui_banner(){
 	while IFS= read -r line; do
 		printf "\033[38;5;$(($$ % 60))m%*s\033[0m\n" "$(((${#line}+termcols)/2))" "${line}"
 	done <<-"EOF"
-	  _   _                         _                
-	 | | | | __ _ _   _  __ _ _ __ (_)_ __ ___   ___ 
-	 | |_| |/ _` | | | |/ _` | '_ \| | '_ ` _ \ / _ \
-	 |  _  | (_| | |_| | (_| | | | | | | | | | |  __/
-	 |_| |_|\__,_|\__, |\__,_|_| |_|_|_| |_| |_|\___|
-							     |___/			早にめ。。。
+	 _   _                         _                
+	| | | | __ _ _   _  __ _ _ __ (_)_ __ ___   ___ 
+	| |_| |/ _` | | | |/ _` | '_ \| | '_ ` _ \ / _ \
+	|  _  | (_| | |_| | (_| | | | | | | | | | |  __/
+	|_| |_|\__,_|\__, |\__,_|_| |_|_|_| |_| |_|\___|
+	                           |___/           早にめ。。。
 	EOF
 }
 
